# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37

instance_class: F4_HIGHMEM

# automatic_scaling:
#
#     max_instances: 1


handlers:

    - url: /robots.txt
      static_files: robots.txt
      upload: robots.txt

    - url: /favicon\.ico
      static_files: chcko/chcko/static/favicon.ico
      upload: chcko/chcko/static/favicon\.ico
      mime_type: image/x-icon

    - url: /static
      static_dir: chcko/chcko/static

    - url: /.*
      script: auto
      secure: always

