# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37

automatic_scaling:

    max_instances: 1


handlers:

    - url: /favicon\.ico
      static_files: mamchecker/static/favicon.ico
      upload: mamchecker/static/favicon\.ico
      mime_type: image/x-icon

    - url: /static
      static_dir: mamchecker/static

    - url: /[^/]*/_images
      static_dir: mamchecker/_images

    - url: .*
      script: mamchecker.app.app
      secure: optional

skip_files:

    - ^(.*/)?#.*#
    - ^(.*/)?.*~
    - ^(.*/)?.*\.py[co]
    - ^(.*/)?.*/RCS/.*
    - ^(.*/)?\..*
    - ^(.*/)?\.rst

