# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37

automatic_scaling:

    max_instances: 1


handlers:

    - url: /favicon\.ico
      static_files: chcko/chcko/static/favicon.ico
      upload: chcko/chcko/static/favicon\.ico
      mime_type: image/x-icon

    - url: /static
      static_dir: chcko/chcko/static

    - url: /[^/]*/_images
      static_dir: chcko/chcko/_images

    - url: .*
      script: chcko.chcko.app.app
      secure: optional

skip_files:

    - ^(.*/)?#.*#
    - ^(.*/)?.*~
    - ^(.*/)?.*\.py[co]
    - ^(.*/)?.*/RCS/.*
    - ^(.*/)?\..*
    - ^(.*/)?\.rst

